version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: smart-clinic-web
    restart: always
    ports:
      - "5137:5137"
    environment:
      UPSTREAM_URL: http://host.docker.internal:6039
    networks:
      - medical-net

networks:
  medical-net:
    driver: bridge
